version: "3.8"  # Ensure you're using a proper version

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: mypass
      POSTGRES_USER: myuser
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - drnet

  simulator:
    image: python:3.10-slim
    container_name: dr-sim
    working_dir: /app
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock  # <-- THIS LINE!
    command: ["bash", "-c", "apt update && apt install -y docker.io curl && pip install fastapi uvicorn && uvicorn app:app --host 0.0.0.0 --port 8000"]
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - drnet

volumes:
  pgdata:

networks:
  drnet:
